server {
    listen 80;

    server_name localhost;
    server_tokens off;

    set $csp_nonce $request_id;
    sub_filter_once off;
    sub_filter CSP_NONCE $csp_nonce;

    add_header Content-Security-Policy "default-src 'self'; img-src 'self'; connect-src 'self' *.googleapis.com; font-src 'self' fonts.gstatic.com; style-src 'self' 'nonce-$csp_nonce' fonts.googleapis.com; script-src 'self' 'nonce-$csp_nonce'" always;
    add_header Permissions-Policy "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()" always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;

    root /usr/share/nginx/html;

    location / {
      index index.html;
      try_files $uri $uri/ /index.html =404;
    }
}
